---
site:
  robots: allow
  title: Fabrice Flore-Thebault
  start_page: ROOT::index.adoc
  url: https://flore-thebault.com
content:
  sources:
    - url: ./
      branches: HEAD
      edit_url: "https://github.com/themr0c/themr0c.github.io/edit/main/{path}"
output:
  destinations:
    - clean: true
      path: build/site
      provider: fs
runtime:
  cache_dir: ./.cache/antora
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
urls:
  html_extension_style: indexify
  redirect_facility: static
